# Generated by Django 4.1.7 on 2023-07-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_type', models.CharField(max_length=100)),
                ('Sales_Person', models.CharField(max_length=100)),
                ('Default_Delivery_Address', models.CharField(max_length=100)),
                ('Default_Warehouse', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('print_quote', models.BooleanField(default=False)),
                ('print_invoice', models.BooleanField(default=False)),
                ('print_packing_slip', models.BooleanField(default=False)),
                ('Obselete', models.BooleanField(default=False)),
                ('Stop_Credit', models.BooleanField(default=False)),
                ('GST_Number', models.CharField(max_length=100, verbose_name='GST / VAT Number')),
                ('Default_Currency', models.CharField(max_length=100)),
                ('Taxable', models.BooleanField(default=False)),
                ('Tax_Rate', models.CharField(max_length=100)),
                ('Sales_Account', models.CharField(max_length=100)),
                ('Bank_Account_Name', models.CharField(max_length=100)),
                ('Bank_Account_Number', models.CharField(max_length=100)),
                ('Payments_Terms', models.CharField(max_length=100)),
                ('Sell_Price_Tier', models.CharField(max_length=100)),
                ('Discount', models.CharField(max_length=20)),
            ],
        ),
    ]
