# Generated by Django 4.1.7 on 2023-07-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0002_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_category', models.CharField(max_length=100)),
                ('dealer', models.CharField(max_length=100)),
                ('unit_of_measure', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('availability', models.BooleanField(default=False)),
                ('delivery', models.BooleanField(default=False)),
                ('deliver_charges', models.BooleanField(default=False)),
                ('height', models.CharField(max_length=10)),
                ('width', models.CharField(max_length=10)),
                ('depth', models.CharField(max_length=10)),
                ('is_premium', models.BooleanField(default=False)),
                ('different_sizes', models.BooleanField(default=False)),
                ('pack_size_category', models.CharField(max_length=100)),
                ('previous_price', models.CharField(max_length=100)),
                ('current_price', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=100)),
            ],
        ),
    ]
